### ISSUE TITLE
Region of Interested for MCAs need a reasonable name?

### ISSUE THREAD

**Issue by Henry0422** [Beamlines-CanadianLightSource/SGM-Beamline#12]
I would like to know how to name the Region of Interest for MCAs since user may require to type in these name (Strings) when they call functions.  Shall we call these ROI or SDD? 

Once we have a decision, I will do refactoring (renaming) all the relevant variables, plots and strings.

Thanks.

**Comment by JamesJDynes** [comment]
I think if we call them pfy_sdd that would reflect us selecting a region of interest from the MCA

**Comment by regiert** [comment]
Using ROI is more correct.  Since you can have multiple ROIs on each detector, I think we will have to use two indices to identify each ROI.  Something like 'roi_*detector_number*' 'roi_1_1' to identify the first ROI on detector 1 and 'roi_4_2' to identify the second ROI on detector 4.

**Comment by JamesJDynes** [comment]
We are selecting the pfy of the tfy, using a roi of the mca to derive the pfy.  So I think pfy is more appropriate than roi-  pfy has scientific meaning.  If we use roi_1 to represent region 1, the range is not standard.  I would prefer we do not assign a region number but instead show the roi we used on the plot, as part of the title.  Also, to include a region number gets more complicated for the user and more complicated to program and we will not use the roi in the analysis.  Something simple like pfy_sdd1, pfy_sdd2, etc.

**Comment by Henry0422** [comment]
Code refactoring complete, and now users just need to input SDD instead of MCA. 
- If it is related to SDD, then passing the SDD string parameter into a function is  similar to this: `plot_sdd_division(mean_energy_array, avg_sdd, "SDD3", "SDD1", 50, 80)`
- if it is related to PFY_SDD, then passing PFY_SDD string parameter into a function is similar to this: `export_data("data/output_avg_pfy_sdd1.xas" ,file_directory, mean_energy_array, "PFY_SDD1", avg_scaler, pfy_data)`

For more details please check No.56 commmit https://github.com/Beamlines-CanadianLightSource/SGM-Beamline/commit/eb3e56a022ed0e110731b6a0c72d744fa8df73dc

Also, there are variables to remind users about which one is start energy of ROI and which one is stop energy of ROI

Some variables in `average_plot.py`, `summary_plot` and `basic_plot` are still using mca prefix, so this may need more refactoring and renaming in the coming future.
