### ISSUE TITLE
generateSummary Plot output turn off

### ISSUE THREAD

**Issue by JamesJDynes** [Beamlines-CanadianLightSource/SGM-Beamline#7]
When you run generateSummaryPlot

You show the output 
Total scan: 51
index of the for loop is :0
Scan No. 1
Parsing MCA's
Done!
 etc.etc.

Only show the Total scan, otherwise turn-off the other.

**Comment by Henry0422** [comment]
These outputs have been commented out now. Outputs are only for developing and debugging.

Cheers! :smile:
